[package]
name = "rusty_f1"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = "2.12.0"
ndarray = "0.16.1"
plotly = "0.13.5"
polars = {version = "0.51.0" , features = ["ndarray", "lazy"] }
rayon = "1.10"
serde = "1.0.228"
serde_json = "1.0.145"
